### ISSUE TITLE
Loading an array of files with one of them empty throws parsing error

### ISSUE THREAD

**Issue by MtDalPizzol** [kof/node-cjson#14]
Hi. I'm building a system where I need to allow some JSON files to exist even if they are empty.
The problem is that when I load an array of files, and one of them is empty, and then parse the result, I'm getting the following error message:

```Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'EOF'"```

**Code sample:**

```javascript
var contents = cjson.load(['file1.json', 'emptyFile.json', 'file3.json'], true);

// both of these fails
var json = JSON.stringify(contents);
var json = JSON.stringify(JSON.parse(contents));
```

Ideas?

**Comment by kof** [comment]
Any chance to put empy obj into those empty files? they are finally json files .... they can't be empty by definition ....)

**Comment by kof** [comment]
If its really necessary send me a PR with a check for empty file, also don't forget to trim the content before checking ...
