### ISSUE TITLE
Remove BOM characters from JSON file before parsing

### ISSUE THREAD

**Issue by mmukarram** [kof/node-cjson#20]
With the most recent version bump from 0.3.1 to 0.3.2, the dependency migration for the parser from `jsonlint` to `json-parse-helpfulerror` breaks when processing JSON files that have Byte-order Mark characters. Since the JSON files are already being loaded with UTF-8 encoding, it would make sense to remove these characters.

Planning on modifying the following lines (and tests) and sending a pull request :
```javascript
    data = fs.readFileSync(path, 'utf-8');
 
   // data = data.replace(/\UFEFF/g, '');

    if (options.replace) {
        data = exports.replace(data, options.replace);
    }
```

**Comment by kof** [comment]
thanks, will accept a PR
