### ISSUE TITLE
Feature request: An option to ignore missing config files

### ISSUE THREAD

**Issue by Munawwar** [kof/node-cjson#27]
In a project, I've got to merge multiple config files together. If one of the environment specific files doesn't exist then it would need to merge whatever files that exists (among the list of specified files).
Example:
```
cjson.load([
  'project1-env1.cjson',
  'project1-default.cjson',
  'env1.cjson',
  'default.cjson'
], true);
```
So if env1.cjson doesn't exist then merge the rest.

But implementing this as the default behavior could conceal missing config files (that wasn't intended to be missing). So..to not break backwards compatibility, how about an option like `ignoreMissingFiles: true`?

If you are ok with the feature request, I could give a shot at implementing it.

**Comment by kof** [comment]
I think its ok to ignore missing files by default.

**Comment by kof** [comment]
And yes, send me a pr with a test and I will merge.

**Comment by Munawwar** [comment]
Pr #28 (forgot to write that in the commit message)

**Comment by kof** [comment]
published
